import React, { useState, useEffect, useMemo } from 'react';
import { compileJsonSchema, validateJsonAgainstSchema, type SchemaValidationError } from '../utils-engine/json-schema';
import { formatJson, minifyJson, validateJson } from '../utils-engine/json';

// Clipboard helper
const copyToClipboard = (text: string): boolean => {
  if (navigator.clipboard && window.isSecureContext) {
    try {
      navigator.clipboard.writeText(text);
      return true;
    } catch {
      // Fallback
    }
  }

  const textArea = document.createElement('textarea');
  textArea.value = text;
  textArea.style.position = 'fixed';
  textArea.style.top = '0';
  textArea.style.left = '0';
  textArea.style.width = '2em';
  textArea.style.height = '2em';
  textArea.style.padding = '0';
  textArea.style.border = 'none';
  textArea.style.outline = 'none';
  textArea.style.boxShadow = 'none';
  textArea.style.background = 'transparent';
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();
  try {
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch (err) {
    document.body.removeChild(textArea);
    return false;
  }
};

// JSON presets
const PRESETS = {
  user: {
    name: 'User Profile',
    json: `{
  "id": "usr_998372",
  "username": "dev_coder_99",
  "email": "coder@useutils.com",
  "isActive": true,
  "profile": {
    "firstName": "Alex",
    "lastName": "Rivera",
    "avatarUrl": "https://useutils.com/avatars/alex.png"
  },
  "roles": ["developer", "admin"],
  "joinedAt": "2026-06-17T12:00:00Z"
}`
  },
  order: {
    name: 'E-Commerce Order',
    json: `{
  "orderId": "ord_8871029",
  "customerEmail": "shopper@mail.com",
  "shippingAddress": {
    "street": "100 Pine Street",
    "city": "San Francisco",
    "state": "CA",
    "zipCode": "94111",
    "country": "USA"
  },
  "items": [
    {
      "productId": "prod_a1",
      "name": "Mechanical Keyboard",
      "price": 149.99,
      "quantity": 1
    },
    {
      "productId": "prod_b2",
      "name": "Coiled USB-C Cable",
      "price": 29.50,
      "quantity": 2
    }
  ],
  "totalPrice": 208.99,
  "isPaid": true,
  "notes": null
}`
  },
  api: {
    name: 'API Config',
    json: `{
  "serviceName": "authentication-gateway",
  "port": 8080,
  "enableHttps": false,
  "endpoints": {
    "/auth/login": { "rateLimit": 100, "public": true },
    "/auth/signup": { "rateLimit": 50, "public": true },
    "/api/users": { "rateLimit": 1000, "public": false }
  },
  "allowedOrigins": [
    "https://useutils.com",
    "http://localhost:3000"
  ],
  "retryInterval": 1.5
}`
  },
  iot: {
    name: 'IoT Telemetry',
    json: `{
  "deviceId": "temp_sensor_north_04",
  "timestamp": "2026-06-17T13:30:00Z",
  "status": "online",
  "readings": {
    "temperatureCelsius": 22.45,
    "humidityPercent": 48.2,
    "batteryVoltage": 3.72
  },
  "alertsTriggered": []
}`
  }
};

export const JsonSchemaValidator: React.FC = () => {
  // Tabs: 'generate' | 'validate'
  const [activeTab, setActiveTab] = useState<'generate' | 'validate'>('generate');

  // Schema Generator State
  const [genInput, setGenInput] = useState<string>('');
  const [genTitle, setGenTitle] = useState<string>('Generated Schema');
  const [genDescription, setGenDescription] = useState<string>('Autogenerated JSON Schema');
  const [genDraft, setGenDraft] = useState<'draft-04' | 'draft-07' | 'draft-2019-09'>('draft-07');
  const [genRequiredAll, setGenRequiredAll] = useState<boolean>(true);
  const [genDetectFormats, setGenDetectFormats] = useState<boolean>(true);
  const [genIncludeDesc, setGenIncludeDesc] = useState<boolean>(true);
  const [genIncludeEx, setGenIncludeEx] = useState<boolean>(true);
  const [genMergeArrays, setGenMergeArrays] = useState<boolean>(true);
  
  const [genOutput, setGenOutput] = useState<string>('');
  const [genInputError, setGenInputError] = useState<string | null>(null);
  
  // Right-side generator view toggle: 'code' | 'tree'
  const [genRightView, setGenRightView] = useState<'code' | 'tree'>('code');

  // Schema Validator State
  const [valSchemaInput, setValSchemaInput] = useState<string>('');
  const [valInstanceInput, setValInstanceInput] = useState<string>('');
  const [valSchemaError, setValSchemaError] = useState<string | null>(null);
  const [valInstanceError, setValInstanceError] = useState<string | null>(null);
  const [validationErrors, setValidationErrors] = useState<SchemaValidationError[]>([]);
  const [valValidated, setValValidated] = useState<boolean>(false);

  // Clipboard feedbacks
  const [copyFeedback, setCopyFeedback] = useState<string>(''); // 'schema' | 'validation' | ''
  const [treeCopiedPath, setTreeCopiedPath] = useState<string | null>(null);

  // Set default generator input
  useEffect(() => {
    setGenInput(PRESETS.user.json);
  }, []);

  // Update generated schema in real-time
  useEffect(() => {
    if (!genInput.trim()) {
      setGenOutput('');
      setGenInputError(null);
      return;
    }

    const check = validateJson(genInput);
    if (!check.isValid) {
      setGenInputError(check.error || 'Invalid JSON syntax');
      setGenOutput('');
      return;
    }

    setGenInputError(null);
    try {
      const compiled = compileJsonSchema(genInput, {
        draft: genDraft,
        title: genTitle,
        description: genDescription,
        requiredByDefault: genRequiredAll,
        detectFormats: genDetectFormats,
        includeDescriptions: genIncludeDesc,
        includeExamples: genIncludeEx,
        mergeArraySchemas: genMergeArrays,
      });
      setGenOutput(compiled);
    } catch (e: any) {
      setGenOutput(`// Generation Error: ${e.message}`);
    }
  }, [genInput, genTitle, genDescription, genDraft, genRequiredAll, genDetectFormats, genIncludeDesc, genIncludeEx, genMergeArrays]);

  // Handle validator checks
  useEffect(() => {
    setValValidated(false);
    setValidationErrors([]);
    setValSchemaError(null);
    setValInstanceError(null);

    if (!valSchemaInput.trim() || !valInstanceInput.trim()) return;

    // Validate Schema JSON syntax
    const schemaCheck = validateJson(valSchemaInput);
    if (!schemaCheck.isValid) {
      setValSchemaError(schemaCheck.error || 'Invalid Schema JSON Syntax');
      return;
    }

    // Validate Instance JSON syntax
    const instanceCheck = validateJson(valInstanceInput);
    if (!instanceCheck.isValid) {
      setValInstanceError(instanceCheck.error || 'Invalid Instance JSON Syntax');
      return;
    }

    try {
      const schemaObj = JSON.parse(valSchemaInput);
      const instanceObj = JSON.parse(valInstanceInput);
      const errs = validateJsonAgainstSchema(instanceObj, schemaObj);
      setValidationErrors(errs);
      setValValidated(true);
    } catch (e: any) {
      setValSchemaError(`Validation execution failed: ${e.message}`);
    }
  }, [valSchemaInput, valInstanceInput]);

  // Prettify / Minify source JSON
  const handlePrettifyGen = () => {
    if (!genInput.trim()) return;
    try {
      const formatted = formatJson(genInput, 2, false);
      setGenInput(formatted);
    } catch (e: any) {
      setGenInputError(e.message);
    }
  };

  const handleMinifyGen = () => {
    if (!genInput.trim()) return;
    try {
      const minified = minifyJson(genInput);
      setGenInput(minified);
    } catch (e: any) {
      setGenInputError(e.message);
    }
  };

  // Prettify Validator values
  const handlePrettifyValSchema = () => {
    if (!valSchemaInput.trim()) return;
    try {
      const formatted = formatJson(valSchemaInput, 2, false);
      setValSchemaInput(formatted);
    } catch (e: any) {
      setValSchemaError(e.message);
    }
  };

  const handlePrettifyValInstance = () => {
    if (!valInstanceInput.trim()) return;
    try {
      const formatted = formatJson(valInstanceInput, 2, false);
      setValInstanceInput(formatted);
    } catch (e: any) {
      setValInstanceError(e.message);
    }
  };

  // Actions
  const handleCopySchema = () => {
    if (!genOutput) return;
    if (copyToClipboard(genOutput)) {
      setCopyFeedback('schema');
      setTimeout(() => setCopyFeedback(''), 1500);
    }
  };

  const handleDownloadSchema = () => {
    if (!genOutput) return;
    const blob = new Blob([genOutput], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${genTitle.toLowerCase().replace(/[^a-z0-9_-]/g, '_') || 'schema'}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Quick load of generated schema into validator
  const handleLoadGeneratedSchema = () => {
    if (genOutput) {
      setValSchemaInput(genOutput);
    }
  };

  // Load preset for generator
  const loadPresetGen = (key: keyof typeof PRESETS) => {
    setGenInput(PRESETS[key].json);
    setGenTitle(PRESETS[key].name + ' Schema');
  };

  // Collapsible Tree Visualizer Component for Schema
  const SchemaTreeViewer = ({ data }: { data: string }) => {
    let parsed: any = null;
    try {
      parsed = JSON.parse(data);
    } catch (e) {
      return <div className="text-red-400 text-xs font-mono">Invalid Schema JSON for Tree View</div>;
    }

    const TreeItem = ({ name, value, path = '$' }: { name?: string; value: any; path: string }) => {
      const [isOpen, setIsOpen] = useState(true);

      const valType = getJsonType(value);

      const handlePathCopy = (e: React.MouseEvent) => {
        e.stopPropagation();
        if (copyToClipboard(path)) {
          setTreeCopiedPath(path);
          setTimeout(() => setTreeCopiedPath(null), 1000);
        }
      };

      if (valType === 'object') {
        const keys = Object.keys(value);
        return (
          <div className="pl-3.5 border-l border-zinc-800/80 my-1 font-mono text-xs">
            <div 
              className="flex items-center gap-1.5 cursor-pointer hover:bg-zinc-800/30 py-0.5 rounded px-1 group select-none text-zinc-300"
              onClick={() => setIsOpen(!isOpen)}
            >
              <span className="text-[10px] text-zinc-500 w-3 transition-transform" style={{ transform: isOpen ? 'rotate(90deg)' : 'none' }}>
                ▶
              </span>
              {name && <span className="text-purple-400 font-semibold">{name}:</span>}
              <span className="text-zinc-400">Object ({keys.length} properties)</span>
              <button 
                onClick={handlePathCopy}
                className="opacity-0 group-hover:opacity-100 transition-opacity ml-2 text-[9px] bg-zinc-850 hover:bg-zinc-800 border border-zinc-700 text-zinc-400 px-1 py-0.2 rounded font-sans"
              >
                {treeCopiedPath === path ? 'Copied ✓' : 'Copy Path'}
              </button>
            </div>
            {isOpen && (
              <div className="pl-3 mt-0.5 flex flex-col gap-0.5">
                {keys.map(key => (
                  <TreeItem 
                    key={key} 
                    name={key} 
                    value={value[key]} 
                    path={path === '$' ? `$.properties.${key}` : `${path}.properties.${key}`} 
                  />
                ))}
              </div>
            )}
          </div>
        );
      }

      if (valType === 'array') {
        return (
          <div className="pl-3.5 border-l border-zinc-800/80 my-1 font-mono text-xs">
            <div 
              className="flex items-center gap-1.5 cursor-pointer hover:bg-zinc-800/30 py-0.5 rounded px-1 group select-none text-zinc-300"
              onClick={() => setIsOpen(!isOpen)}
            >
              <span className="text-[10px] text-zinc-500 w-3 transition-transform" style={{ transform: isOpen ? 'rotate(90deg)' : 'none' }}>
                ▶
              </span>
              {name && <span className="text-purple-400 font-semibold">{name}:</span>}
              <span className="text-zinc-400">Array [{value.length}]</span>
              <button 
                onClick={handlePathCopy}
                className="opacity-0 group-hover:opacity-100 transition-opacity ml-2 text-[9px] bg-zinc-850 hover:bg-zinc-800 border border-zinc-700 text-zinc-400 px-1 py-0.2 rounded font-sans"
              >
                {treeCopiedPath === path ? 'Copied ✓' : 'Copy Path'}
              </button>
            </div>
            {isOpen && (
              <div className="pl-3 mt-0.5 flex flex-col gap-0.5">
                {value.map((item: any, idx: number) => (
                  <TreeItem 
                    key={idx} 
                    name={`[${idx}]`} 
                    value={item} 
                    path={`${path}.items`} // standard JSON schema items definition path
                  />
                ))}
              </div>
            )}
          </div>
        );
      }

      // Scalar node
      const displayVal = typeof value === 'string' ? `"${value}"` : String(value);
      let colorClass = 'text-zinc-300';
      if (typeof value === 'boolean') colorClass = 'text-yellow-500';
      if (typeof value === 'number') colorClass = 'text-blue-400';
      if (value === null) colorClass = 'text-red-400';

      return (
        <div className="pl-3.5 border-l border-zinc-800/80 py-0.5 my-0.5 font-mono text-xs flex items-center gap-1 group hover:bg-zinc-800/10 px-1 rounded">
          {name && <span className="text-emerald-400 font-semibold mr-1">{name}:</span>}
          <span className={`${colorClass} truncate max-w-xs md:max-w-md`}>{displayVal}</span>
          <button 
            onClick={handlePathCopy}
            className="opacity-0 group-hover:opacity-100 transition-opacity ml-2 text-[9px] bg-zinc-850 hover:bg-zinc-800 border border-zinc-700 text-zinc-400 px-1 py-0.2 rounded font-sans"
          >
            {treeCopiedPath === path ? 'Copied ✓' : 'Copy Path'}
          </button>
        </div>
      );
    };

    return (
      <div className="overflow-y-auto max-h-[450px] p-2 flex flex-col gap-1 select-text">
        <TreeItem value={parsed} path="$" />
      </div>
    );
  };

  return (
    <div className="w-full max-w-7xl mx-auto flex flex-col gap-6">
      
      {/* Mode Navigation Tabs */}
      <div className="flex gap-2 bg-panel border border-border-hairline p-1 rounded-xl w-full max-w-md self-center md:self-start">
        <button
          onClick={() => setActiveTab('generate')}
          className={`flex-1 py-2 rounded-lg text-xs md:text-sm font-mono font-semibold select-none cursor-pointer transition-all ${
            activeTab === 'generate'
              ? 'bg-zinc-850 text-accent-emerald border-border-hairline shadow-sm'
              : 'text-zinc-400 hover:text-zinc-200'
          }`}
        >
          🛡️ Schema Generator
        </button>
        <button
          onClick={() => setActiveTab('validate')}
          className={`flex-1 py-2 rounded-lg text-xs md:text-sm font-mono font-semibold select-none cursor-pointer transition-all ${
            activeTab === 'validate'
              ? 'bg-zinc-850 text-accent-emerald border-border-hairline shadow-sm'
              : 'text-zinc-400 hover:text-zinc-200'
          }`}
        >
          🔍 Schema Validator
        </button>
      </div>

      {/* 1. SCHEMA GENERATOR INTERFACE */}
      {activeTab === 'generate' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-stretch">
          
          {/* Left Pane: Sample Input & Configs */}
          <div className="flex flex-col gap-5 bg-panel border border-border-hairline rounded-xl p-5">
            <div className="flex flex-wrap gap-3 justify-between items-center">
              <h2 className="text-xs uppercase tracking-wider text-zinc-400 font-semibold font-mono">
                Sample JSON Input
              </h2>
              <div className="flex flex-wrap gap-1.5 items-center">
                {/* Presets dropdown */}
                <div className="relative inline-block text-left mr-1">
                  <select
                    onChange={(e) => loadPresetGen(e.target.value as keyof typeof PRESETS)}
                    defaultValue="user"
                    className="bg-zinc-800 hover:bg-zinc-750 text-zinc-300 px-2 py-0.5 text-[10px] rounded border border-zinc-700 outline-none cursor-pointer font-mono"
                  >
                    {Object.keys(PRESETS).map(key => (
                      <option key={key} value={key}>
                        Load: {PRESETS[key as keyof typeof PRESETS].name}
                      </option>
                    ))}
                  </select>
                </div>
                {genInput && (
                  <>
                    <button
                      onClick={handlePrettifyGen}
                      className="px-2 py-0.5 text-[10px] bg-zinc-800 hover:bg-zinc-750 text-zinc-300 rounded border border-zinc-700/60 cursor-pointer font-mono transition-colors"
                    >
                      Prettify
                    </button>
                    <button
                      onClick={handleMinifyGen}
                      className="px-2 py-0.5 text-[10px] bg-zinc-800 hover:bg-zinc-750 text-zinc-300 rounded border border-zinc-700/60 cursor-pointer font-mono transition-colors"
                    >
                      Minify
                    </button>
                    <button
                      onClick={() => setGenInput('')}
                      className="px-2 py-0.5 text-[10px] bg-red-950/40 hover:bg-red-950/80 text-red-400 rounded border border-red-900/60 cursor-pointer font-mono transition-colors"
                    >
                      Clear
                    </button>
                  </>
                )}
              </div>
            </div>

            {/* Input Text Area */}
            <div className="relative flex flex-col min-h-[260px]">
              <textarea
                value={genInput}
                onChange={(e) => setGenInput(e.target.value)}
                placeholder="Paste sample JSON dataset here..."
                className="w-full flex-grow bg-canvas border border-border-hairline focus:border-zinc-750 outline-none rounded-lg p-3 font-mono text-xs md:text-sm text-zinc-200 resize-none leading-relaxed transition-all focus:ring-1 focus:ring-zinc-750 min-h-[260px]"
              />
              {!genInput && (
                <div className="absolute right-3.5 bottom-3.5 flex items-center gap-1.5 pointer-events-none select-none">
                  <kbd className="font-mono bg-zinc-800/80 px-1.5 py-0.5 rounded border border-zinc-700 text-[10px] text-zinc-400">⌘ V</kbd>
                </div>
              )}
            </div>

            {/* Ingestion syntax errors */}
            {genInputError && (
              <div className="bg-red-950/30 border border-red-900/40 rounded-lg p-3 text-red-400 text-xs font-mono leading-relaxed">
                <span className="font-bold">⚠️ JSON Parse Error:</span> {genInputError}
              </div>
            )}

            {/* Advanced configurations */}
            <div className="border-t border-border-hairline/60 pt-4 flex flex-col gap-4">
              <h3 className="text-xs uppercase tracking-wider text-zinc-400 font-semibold font-mono">
                Generator Configurations
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Draft Selection */}
                <div className="flex flex-col gap-1.5">
                  <label className="text-xs font-mono text-zinc-450">Schema Draft Version</label>
                  <div className="flex gap-1 bg-zinc-900/60 border border-border-hairline p-1 rounded-lg">
                    {['draft-07', 'draft-2019-09', 'draft-04'].map((draft) => (
                      <button
                        key={draft}
                        onClick={() => setGenDraft(draft as any)}
                        className={`flex-1 py-1 rounded text-[10px] font-mono select-none cursor-pointer transition-all ${
                          genDraft === draft
                            ? 'bg-zinc-800 text-accent-emerald font-semibold shadow-sm'
                            : 'text-zinc-500 hover:text-zinc-300'
                        }`}
                      >
                        {draft.replace('draft-', 'Draft ')}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Schema Metadata inputs */}
                <div className="flex flex-col gap-1.5">
                  <label className="text-xs font-mono text-zinc-450">Schema Title</label>
                  <input
                    type="text"
                    value={genTitle}
                    onChange={(e) => setGenTitle(e.target.value)}
                    placeholder="E.g., User Profile"
                    className="bg-canvas border border-border-hairline hover:border-zinc-700 focus:border-zinc-650 rounded-lg px-3 py-1.5 text-xs font-mono text-zinc-200 outline-none transition-colors"
                  />
                </div>
              </div>

              {/* Toggles */}
              <div className="flex flex-col gap-2.5 mt-1.5 border-t border-border-hairline/40 pt-3">
                <label className="flex items-center gap-2.5 text-xs font-mono text-zinc-300 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    checked={genRequiredAll}
                    onChange={(e) => setGenRequiredAll(e.target.checked)}
                    className="rounded border-zinc-700 bg-canvas text-accent-emerald focus:ring-0 focus:ring-offset-0 w-3.5 h-3.5 cursor-pointer accent-accent-emerald"
                  />
                  Mark all properties as <code className="text-accent-emerald text-[10px]">"required"</code> by default
                </label>

                <label className="flex items-center gap-2.5 text-xs font-mono text-zinc-300 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    checked={genDetectFormats}
                    onChange={(e) => setGenDetectFormats(e.target.checked)}
                    className="rounded border-zinc-700 bg-canvas text-accent-emerald focus:ring-0 focus:ring-offset-0 w-3.5 h-3.5 cursor-pointer accent-accent-emerald"
                  />
                  Detect string formats (email, datetime, uri, uuid, IP addresses)
                </label>

                <label className="flex items-center gap-2.5 text-xs font-mono text-zinc-300 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    checked={genIncludeDesc}
                    onChange={(e) => setGenIncludeDesc(e.target.checked)}
                    className="rounded border-zinc-700 bg-canvas text-accent-emerald focus:ring-0 focus:ring-offset-0 w-3.5 h-3.5 cursor-pointer accent-accent-emerald"
                  />
                  Generate property descriptions based on field names
                </label>

                <label className="flex items-center gap-2.5 text-xs font-mono text-zinc-300 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    checked={genIncludeEx}
                    onChange={(e) => setGenIncludeEx(e.target.checked)}
                    className="rounded border-zinc-700 bg-canvas text-accent-emerald focus:ring-0 focus:ring-offset-0 w-3.5 h-3.5 cursor-pointer accent-accent-emerald"
                  />
                  Embed source data values as <code className="text-accent-emerald text-[10px]">"examples"</code> arrays
                </label>

                <label className="flex items-center gap-2.5 text-xs font-mono text-zinc-300 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    checked={genMergeArrays}
                    onChange={(e) => setGenMergeArrays(e.target.checked)}
                    className="rounded border-zinc-700 bg-canvas text-accent-emerald focus:ring-0 focus:ring-offset-0 w-3.5 h-3.5 cursor-pointer accent-accent-emerald"
                  />
                  Merge objects in array lists into a single consolidated schema
                </label>
              </div>

            </div>
          </div>

          {/* Right Pane: Generated Outputs */}
          <div className="flex flex-col bg-panel border border-border-hairline rounded-xl p-5 gap-5">
            <div className="flex justify-between items-center">
              <h2 className="text-xs uppercase tracking-wider text-zinc-400 font-semibold font-mono">
                Generated JSON Schema
              </h2>
              <div className="flex gap-2">
                <button
                  onClick={handleDownloadSchema}
                  disabled={!genOutput}
                  className="px-2 py-0.5 text-[10px] bg-zinc-800 hover:bg-zinc-750 text-zinc-300 rounded border border-zinc-700 cursor-pointer font-mono transition-colors disabled:opacity-40 disabled:pointer-events-none"
                >
                  Download (.json)
                </button>
                <button
                  onClick={handleCopySchema}
                  disabled={!genOutput}
                  className="flex items-center gap-1 px-2.5 py-0.5 text-[10px] bg-accent-emerald/10 hover:bg-accent-emerald/20 border border-accent-emerald/20 text-accent-emerald rounded cursor-pointer font-mono font-semibold transition-all disabled:opacity-40 disabled:pointer-events-none"
                >
                  {copyFeedback === 'schema' ? 'Copied ✓' : 'Copy Schema'}
                </button>
              </div>
            </div>

            {/* Toggle format: Raw Code vs Tree View */}
            <div className="flex gap-1 bg-zinc-900/60 border border-border-hairline p-1.5 rounded-lg">
              <button
                onClick={() => setGenRightView('code')}
                className={`flex-1 py-1.5 rounded text-[11px] font-mono select-none cursor-pointer transition-all ${
                  genRightView === 'code'
                    ? 'bg-zinc-800 text-accent-emerald font-semibold shadow-sm'
                    : 'text-zinc-400 hover:text-zinc-200'
                }`}
              >
                Code Schema
              </button>
              <button
                onClick={() => setGenRightView('tree')}
                className={`flex-1 py-1.5 rounded text-[11px] font-mono select-none cursor-pointer transition-all ${
                  genRightView === 'tree'
                    ? 'bg-zinc-800 text-accent-emerald font-semibold shadow-sm'
                    : 'text-zinc-400 hover:text-zinc-200'
                }`}
              >
                Visual tree
              </button>
            </div>

            {/* Output Display box */}
            <div className="flex-grow min-h-[360px] bg-canvas border border-border-hairline rounded-lg p-3 relative overflow-hidden flex flex-col">
              {genRightView === 'code' ? (
                <>
                  <textarea
                    value={genOutput}
                    readOnly
                    placeholder="JSON Schema will compile here automatically as you type..."
                    className="w-full flex-grow bg-transparent font-mono text-xs md:text-sm text-zinc-300 resize-none outline-none leading-relaxed select-all"
                  />
                  {genOutput && (
                    <div className="absolute right-3.5 bottom-3.5 pointer-events-none select-none">
                      <kbd className="font-mono bg-zinc-800/90 px-1.5 py-0.5 rounded border border-zinc-700 text-[10px] text-zinc-500">⌘ C</kbd>
                    </div>
                  )}
                </>
              ) : (
                <div className="w-full flex-grow overflow-auto">
                  {genOutput ? (
                    <SchemaTreeViewer data={genOutput} />
                  ) : (
                    <span className="text-zinc-500 font-mono text-xs p-2 block">No JSON Schema generated yet. Enter valid JSON first.</span>
                  )}
                </div>
              )}
            </div>

            {/* Quick action to load into Validator */}
            {genOutput && (
              <button
                onClick={() => {
                  handleLoadGeneratedSchema();
                  setActiveTab('validate');
                }}
                className="w-full bg-zinc-900 hover:bg-zinc-850 border border-border-hairline/80 text-accent-emerald hover:text-emerald-350 text-xs font-mono py-2.5 rounded-lg font-semibold transition-colors flex items-center justify-center gap-1.5"
              >
                <span>🛡️ Load Generated Schema Into Validator</span>
                <span className="text-[10px] text-zinc-500 font-normal">→</span>
              </button>
            )}

            {/* Local Privacy Pill */}
            <div className="flex items-center justify-between bg-zinc-900 border border-border-hairline rounded-lg px-3.5 py-2.5">
              <div className="inline-flex items-center gap-2 text-[10px] text-accent-emerald font-mono">
                <span className="w-1.5 h-1.5 rounded-full bg-accent-emerald animate-ping"></span>
                Processed locally in browser. Zero server transmission.
              </div>
              <span className="text-[10px] text-zinc-500 font-mono">Privacy Guaranteed</span>
            </div>

          </div>

        </div>
      )}

      {/* 2. SCHEMA VALIDATOR INTERFACE */}
      {activeTab === 'validate' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-stretch">
          
          {/* Left Pane: Dual Inputs (Schema + Instance JSON) */}
          <div className="flex flex-col gap-6 bg-panel border border-border-hairline rounded-xl p-5">
            
            {/* Input 1: JSON Schema */}
            <div className="flex flex-col gap-3">
              <div className="flex justify-between items-center">
                <h2 className="text-xs uppercase tracking-wider text-zinc-400 font-semibold font-mono">
                  1. JSON Schema Definition
                </h2>
                <div className="flex gap-2">
                  {genOutput && (
                    <button
                      onClick={handleLoadGeneratedSchema}
                      className="px-2 py-0.5 text-[10px] bg-accent-emerald/10 border border-accent-emerald/20 text-accent-emerald hover:bg-accent-emerald/20 rounded cursor-pointer font-mono font-medium transition-colors"
                    >
                      Use Generated Schema
                    </button>
                  )}
                  {valSchemaInput && (
                    <>
                      <button
                        onClick={handlePrettifyValSchema}
                        className="px-1.5 py-0.2 text-[9px] bg-zinc-800 hover:bg-zinc-750 text-zinc-300 rounded border border-zinc-700/60 cursor-pointer font-mono"
                      >
                        Prettify
                      </button>
                      <button
                        onClick={() => setValSchemaInput('')}
                        className="px-1.5 py-0.2 text-[9px] bg-red-950/20 hover:bg-red-950/40 text-red-400 rounded border border-red-900/30 cursor-pointer font-mono"
                      >
                        Clear
                      </button>
                    </>
                  )}
                </div>
              </div>
              
              <div className="relative flex flex-col min-h-[180px]">
                <textarea
                  value={valSchemaInput}
                  onChange={(e) => setValSchemaInput(e.target.value)}
                  placeholder={`Paste JSON Schema here... (e.g. { "type": "object", "properties": { ... } })`}
                  className="w-full flex-grow bg-canvas border border-border-hairline focus:border-zinc-750 outline-none rounded-lg p-3 font-mono text-xs md:text-sm text-zinc-200 resize-none leading-relaxed transition-all focus:ring-1 focus:ring-zinc-750 min-h-[180px]"
                />
                {!valSchemaInput && (
                  <div className="absolute right-3.5 bottom-3.5 flex items-center gap-1.5 pointer-events-none select-none">
                    <kbd className="font-mono bg-zinc-800/80 px-1.5 py-0.5 rounded border border-zinc-700 text-[10px] text-zinc-400">⌘ V</kbd>
                  </div>
                )}
              </div>

              {valSchemaError && (
                <div className="bg-red-950/30 border border-red-900/40 rounded-lg p-3 text-red-400 text-xs font-mono leading-relaxed">
                  <span className="font-bold">⚠️ Schema JSON Error:</span> {valSchemaError}
                </div>
              )}
            </div>

            {/* Input 2: JSON Instance Data */}
            <div className="flex flex-col gap-3 border-t border-border-hairline/60 pt-5">
              <div className="flex justify-between items-center">
                <h2 className="text-xs uppercase tracking-wider text-zinc-400 font-semibold font-mono">
                  2. JSON Instance Data (Payload to test)
                </h2>
                <div className="flex gap-2">
                  {valInstanceInput && (
                    <>
                      <button
                        onClick={handlePrettifyValInstance}
                        className="px-1.5 py-0.2 text-[9px] bg-zinc-800 hover:bg-zinc-750 text-zinc-300 rounded border border-zinc-700/60 cursor-pointer font-mono"
                      >
                        Prettify
                      </button>
                      <button
                        onClick={() => setValInstanceInput('')}
                        className="px-1.5 py-0.2 text-[9px] bg-red-950/20 hover:bg-red-950/40 text-red-400 rounded border border-red-900/30 cursor-pointer font-mono"
                      >
                        Clear
                      </button>
                    </>
                  )}
                </div>
              </div>

              <div className="relative flex flex-col min-h-[180px]">
                <textarea
                  value={valInstanceInput}
                  onChange={(e) => setValInstanceInput(e.target.value)}
                  placeholder="Paste JSON instance dataset to validate against the schema..."
                  className="w-full flex-grow bg-canvas border border-border-hairline focus:border-zinc-750 outline-none rounded-lg p-3 font-mono text-xs md:text-sm text-zinc-200 resize-none leading-relaxed transition-all focus:ring-1 focus:ring-zinc-750 min-h-[180px]"
                />
                {!valInstanceInput && (
                  <div className="absolute right-3.5 bottom-3.5 flex items-center gap-1.5 pointer-events-none select-none">
                    <kbd className="font-mono bg-zinc-800/80 px-1.5 py-0.5 rounded border border-zinc-700 text-[10px] text-zinc-400">⌘ V</kbd>
                  </div>
                )}
              </div>

              {valInstanceError && (
                <div className="bg-red-950/30 border border-red-900/40 rounded-lg p-3 text-red-400 text-xs font-mono leading-relaxed">
                  <span className="font-bold">⚠️ Instance JSON Error:</span> {valInstanceError}
                </div>
              )}
            </div>

          </div>

          {/* Right Pane: Validation Outcomes */}
          <div className="flex flex-col bg-panel border border-border-hairline rounded-xl p-5 gap-5 justify-between">
            
            <div className="flex flex-col gap-4 flex-grow">
              <h2 className="text-xs uppercase tracking-wider text-zinc-400 font-semibold font-mono">
                Validation Outcome
              </h2>

              {!valValidated ? (
                <div className="flex-grow flex flex-col items-center justify-center py-20 text-center gap-3 border border-border-hairline border-dashed rounded-lg bg-zinc-900/20">
                  <span className="text-3xl">🛡️</span>
                  <div className="flex flex-col gap-1 max-w-xs">
                    <span className="text-xs font-mono text-zinc-300 font-semibold">Awaiting input data</span>
                    <p className="text-[11px] text-zinc-500 font-sans leading-relaxed">
                      Provide both the JSON Schema and an Instance JSON payload on the left to begin validation.
                    </p>
                  </div>
                </div>
              ) : validationErrors.length === 0 ? (
                /* Success Compliance State */
                <div className="flex-grow bg-emerald-950/15 border border-accent-emerald/25 rounded-lg p-6 flex flex-col items-center justify-center text-center gap-4 py-16">
                  <div className="w-12 h-12 rounded-full bg-accent-emerald/10 border border-accent-emerald/30 flex items-center justify-center text-accent-emerald text-xl select-none">
                    ✓
                  </div>
                  <div className="flex flex-col gap-1.5 max-w-sm">
                    <h3 className="text-base font-bold font-mono text-accent-emerald">
                      JSON Schema Compliant
                    </h3>
                    <p className="text-xs text-zinc-400 font-sans leading-relaxed">
                      Your JSON instance conforms perfectly to the specified schema constraints. Real-time evaluations completed locally in browser.
                    </p>
                  </div>
                </div>
              ) : (
                /* Violation Warnings State */
                <div className="flex-grow flex flex-col gap-3">
                  <div className="bg-red-950/20 border border-red-900/35 rounded-lg p-4 flex items-center gap-3">
                    <span className="text-xl select-none">⚠️</span>
                    <div>
                      <h3 className="text-xs font-mono font-bold text-red-400">
                        Schema Violations Found ({validationErrors.length})
                      </h3>
                      <p className="text-[10px] text-zinc-450 font-sans leading-normal mt-0.5">
                        Your JSON instance fails to comply with some constraints of the schema definitions.
                      </p>
                    </div>
                  </div>

                  {/* Scrollable validation issues list */}
                  <div className="flex-grow overflow-y-auto max-h-[360px] border border-border-hairline rounded-lg bg-canvas divide-y divide-border-hairline/60">
                    {validationErrors.map((err, idx) => (
                      <div 
                        key={idx} 
                        className="p-3 text-xs font-mono flex flex-col gap-1.5 hover:bg-zinc-900/40 group relative cursor-pointer"
                        onClick={() => {
                          if (copyToClipboard(err.path)) {
                            setTreeCopiedPath(err.path);
                            setTimeout(() => setTreeCopiedPath(null), 1000);
                          }
                        }}
                      >
                        <div className="flex items-center justify-between">
                          <span className="text-accent-emerald font-semibold break-all mr-4">{err.path}</span>
                          <span className="text-[9px] bg-red-950/40 border border-red-900/40 text-red-400 px-1.5 py-0.2 rounded uppercase tracking-wide">
                            {err.keyword}
                          </span>
                        </div>
                        <p className="text-zinc-350 pr-12">{err.message}</p>
                        <span className="absolute right-3.5 bottom-3 text-[9px] text-zinc-500 opacity-0 group-hover:opacity-100 transition-opacity">
                          {treeCopiedPath === err.path ? 'Copied path ✓' : 'Click to copy path'}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Privacy status & status pill */}
            <div className="flex items-center justify-between bg-zinc-900 border border-border-hairline rounded-lg px-3.5 py-2.5 mt-4">
              <div className="inline-flex items-center gap-2 text-[10px] text-accent-emerald font-mono">
                <span className="w-1.5 h-1.5 rounded-full bg-accent-emerald animate-ping"></span>
                Processed locally in browser. Zero server transmission.
              </div>
              <span className="text-[10px] text-zinc-500 font-mono">Privacy Guaranteed</span>
            </div>

          </div>

        </div>
      )}

    </div>
  );
};
